apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${deploymentName}
  name: ${deploymentName}
spec:
  replicas: ${JobRep}
  selector:
    matchLabels:
      app: ${deploymentName}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${deploymentName}
    spec:
      containers:
      - env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        image: ${RegistryUrl}/cloudhos/${JobEnv}/2.0/${JobName}:${BuildNum}
        livenessProbe:
          failureThreshold: 60
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        name: ${deploymentName}
        readinessProbe:
          failureThreshold: 60
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        resources:
          limits:
            cpu: ${DockerCpu}
            memory: ${DockerMem}
          requests:
            cpu: 50m
            memory: 1Gi
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /etc/hosts
          name: hosts
          subPath: hosts
        - mountPath: /etc/resolv.conf
          name: resolv
        - mountPath: /opt/logs
          name: logs
      hostname: localhost
      imagePullSecrets:
      - name: regcred
      initContainers:
      - image: swr.cn-east-2.myhuaweicloud.com/common-server/alpine-init:2.0
        name: check-healthy
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: localtime
      - configMap:
          defaultMode: 420
          name: hosts
        name: hosts
      - hostPath:
          path: /etc/resolv.conf
        name: resolv
      - hostPath:
          path: /opt/project/project-log/${JobEnv}/${deploymentName}/logs
        name: logs