apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.1.21
  name: management-test
  namespace: local-test
spec:
  loadBalancerIP: 192.168.1.21
  ports:
  - name: server
    port: 9009
    protocol: TCP
    targetPort: 9009
  - name: debug
    port: 20035
    protocol: TCP
    targetPort: 5005
  selector:
    app: management-test
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: management-test
  name: management-test
  namespace: local-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-test
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: management-test
    spec:
      containers:
      - env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        image: swr.cn-east-2.myhuaweicloud.com/cloudhos/local-test/2.0/management_test:957
        livenessProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/liveness
            port: 10000
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: management-test
        readinessProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/readiness
            port: 10000
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 2G
          requests:
            cpu: 50m
            memory: 1Gi
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /etc/hosts
          name: hosts
          subPath: hosts
        - mountPath: /etc/resolv.conf
          name: resolv
        - mountPath: /opt/logs
          name: logs
      hostname: localhost
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: localtime
      - configMap:
          defaultMode: 420
          name: hosts
        name: hosts
      - hostPath:
          path: /etc/resolv.conf
        name: resolv
      - hostPath:
          path: /opt/project/project-log/local-test/management-test/logs
        name: logs
